In [1]:
using Random
using LinearAlgebra
rng = MersenneTwister(2018)
import LinearAlgebra.dot
import LinearAlgebra.norm
import LinearAlgebra.triu
import LinearAlgebra.diag
using Printf
;

In [2]:
#A = [2 -4 5; 2 1 -3; 1 2 -6]
#A = [2 -1 4; 3 4 -2; 1 4 2; -4 -1 3]
#A = [1 3; 1 2]
ϵ = 10^-10
A = [1 1 1; ϵ 0 0; 0 ϵ 0; 0 0 ϵ]
A = float(A)
A0 = copy(A)
B0 = copy(A)
C0 = copy(A)

4×3 Matrix{Float64}:
 1.0      1.0      1.0
 1.0e-10  0.0      0.0
 0.0      1.0e-10  0.0
 0.0      0.0      1.0e-10

In [3]:
# function geqrfCGS!(A)
    m = size(A,1)
    n = size(A,2)
    @assert m >= n
    R = zeros(Float64, n,n)
    for j=1:n
      display("j=")
      display(j)
        # Orthogonalize
        for i=1:j-1, k=1:m
            R[i,j] += A[k,i] * A[k,j]
        end
        for i=1:j-1, k=1:m
            A[k,j] -= A[k,i] * R[i,j]
        end
        R[j,j] = norm( A[:,j] )
        display("Orthogonal columns of A before Normalization")
        display(A)
        display("Matrix R")
        display(R)
        # Normalize column
        A[:,j] /= R[j,j]
    display("Orthogonal columns of A after Normalization")
    display(A)
    end
    display("Q")
    display(A)
    # A contains the Q factor at the end
    display("R")
    display(R)
#     return R
# end

"j="

1

"Orthogonal columns of A before Normalization"

4×3 Matrix{Float64}:
 1.0      1.0      1.0
 1.0e-10  0.0      0.0
 0.0      1.0e-10  0.0
 0.0      0.0      1.0e-10

"Matrix R"

3×3 Matrix{Float64}:
 1.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

"Orthogonal columns of A after Normalization"

4×3 Matrix{Float64}:
 1.0      1.0      1.0
 1.0e-10  0.0      0.0
 0.0      1.0e-10  0.0
 0.0      0.0      1.0e-10

"j="

2

"Orthogonal columns of A before Normalization"

4×3 Matrix{Float64}:
 1.0       0.0      1.0
 1.0e-10  -1.0e-10  0.0
 0.0       1.0e-10  0.0
 0.0       0.0      1.0e-10

"Matrix R"

3×3 Matrix{Float64}:
 1.0  1.0          0.0
 0.0  1.41421e-10  0.0
 0.0  0.0          0.0

"Orthogonal columns of A after Normalization"

4×3 Matrix{Float64}:
 1.0       0.0       1.0
 1.0e-10  -0.707107  0.0
 0.0       0.707107  0.0
 0.0       0.0       1.0e-10

"j="

3

"Orthogonal columns of A before Normalization"

4×3 Matrix{Float64}:
 1.0       0.0        0.0
 1.0e-10  -0.707107  -1.0e-10
 0.0       0.707107   0.0
 0.0       0.0        1.0e-10

"Matrix R"

3×3 Matrix{Float64}:
 1.0  1.0          1.0
 0.0  1.41421e-10  0.0
 0.0  0.0          1.41421e-10

"Orthogonal columns of A after Normalization"

4×3 Matrix{Float64}:
 1.0       0.0        0.0
 1.0e-10  -0.707107  -0.707107
 0.0       0.707107   0.0
 0.0       0.0        0.707107

"Q"

4×3 Matrix{Float64}:
 1.0       0.0        0.0
 1.0e-10  -0.707107  -0.707107
 0.0       0.707107   0.0
 0.0       0.0        0.707107

"R"

3×3 Matrix{Float64}:
 1.0  1.0          1.0
 0.0  1.41421e-10  0.0
 0.0  0.0          1.41421e-10

In [4]:
A'*A #Q^T * Q

3×3 Matrix{Float64}:
  1.0          -7.07107e-11  -7.07107e-11
 -7.07107e-11   1.0           0.5
 -7.07107e-11   0.5           1.0

In [5]:
A*R # Q*R

4×3 Matrix{Float64}:
 1.0       1.0           1.0
 1.0e-10  -3.62325e-27  -3.62325e-27
 0.0       1.0e-10       0.0
 0.0       0.0           1.0e-10

In [6]:
A0  # matrix A

4×3 Matrix{Float64}:
 1.0      1.0      1.0
 1.0e-10  0.0      0.0
 0.0      1.0e-10  0.0
 0.0      0.0      1.0e-10

In [7]:
function geqrfMGS!(A)
    m = size(A,1)
    n = size(A,2)
    @assert m >= n
    R = zeros(Float64, n,n)
    for j=1:n
        # Orthogonalize
        for i=1:j-1
            for k=1:m
                R[i,j] += A[k,i] * A[k,j]
            end
            for k=1:m
                A[k,j] -= A[k,i] * R[i,j]
            end
        end
        display("Orthogonal columns of A before Normalization")
        display(A)
        # Normalize column
        R[j,j] = norm( A[:,j] )
        A[:,j] /= R[j,j]
        display("matrix R")
        display(R)
        display("Orthogonal columns of A after Normalization")
        display(A)
    end
    display("Q")
    display(A)
    # A contains the Q factor at the end
    display("R")
    display(R)
    return R
end

geqrfMGS! (generic function with 1 method)

In [8]:
geqrfMGS!(B0)

"Orthogonal columns of A before Normalization"

4×3 Matrix{Float64}:
 1.0      1.0      1.0
 1.0e-10  0.0      0.0
 0.0      1.0e-10  0.0
 0.0      0.0      1.0e-10

"matrix R"

3×3 Matrix{Float64}:
 1.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

"Orthogonal columns of A after Normalization"

4×3 Matrix{Float64}:
 1.0      1.0      1.0
 1.0e-10  0.0      0.0
 0.0      1.0e-10  0.0
 0.0      0.0      1.0e-10

"Orthogonal columns of A before Normalization"

4×3 Matrix{Float64}:
 1.0       0.0      1.0
 1.0e-10  -1.0e-10  0.0
 0.0       1.0e-10  0.0
 0.0       0.0      1.0e-10

"matrix R"

3×3 Matrix{Float64}:
 1.0  1.0          0.0
 0.0  1.41421e-10  0.0
 0.0  0.0          0.0

"Orthogonal columns of A after Normalization"

4×3 Matrix{Float64}:
 1.0       0.0       1.0
 1.0e-10  -0.707107  0.0
 0.0       0.707107  0.0
 0.0       0.0       1.0e-10

"Orthogonal columns of A before Normalization"

4×3 Matrix{Float64}:
 1.0       0.0        0.0
 1.0e-10  -0.707107  -5.0e-11
 0.0       0.707107  -5.0e-11
 0.0       0.0        1.0e-10

"matrix R"

3×3 Matrix{Float64}:
 1.0  1.0          1.0
 0.0  1.41421e-10  7.07107e-11
 0.0  0.0          1.22474e-10

"Orthogonal columns of A after Normalization"

4×3 Matrix{Float64}:
 1.0       0.0        0.0
 1.0e-10  -0.707107  -0.408248
 0.0       0.707107  -0.408248
 0.0       0.0        0.816497

"Q"

4×3 Matrix{Float64}:
 1.0       0.0        0.0
 1.0e-10  -0.707107  -0.408248
 0.0       0.707107  -0.408248
 0.0       0.0        0.816497

"R"

3×3 Matrix{Float64}:
 1.0  1.0          1.0
 0.0  1.41421e-10  7.07107e-11
 0.0  0.0          1.22474e-10

3×3 Matrix{Float64}:
 1.0  1.0          1.0
 0.0  1.41421e-10  7.07107e-11
 0.0  0.0          1.22474e-10

In [9]:
B0' * B0 #Q^T*Q

3×3 Matrix{Float64}:
  1.0          -7.07107e-11  -4.08248e-11
 -7.07107e-11   1.0          -1.54826e-16
 -4.08248e-11  -1.54826e-16   1.0

In [10]:
B0*R #Q*R

4×3 Matrix{Float64}:
 1.0       1.0           1.0
 1.0e-10  -3.62325e-27   4.2265e-11
 0.0       1.0e-10      -5.7735e-11
 0.0       0.0           1.1547e-10

In [11]:
C0 # matrix A 

4×3 Matrix{Float64}:
 1.0      1.0      1.0
 1.0e-10  0.0      0.0
 0.0      1.0e-10  0.0
 0.0      0.0      1.0e-10