In [1]:
using Random
using LinearAlgebra
rng = MersenneTwister(2018)
import LinearAlgebra.dot
import LinearAlgebra.norm
import LinearAlgebra.triu
import LinearAlgebra.diag
using Printf
;

In [2]:
#A = [2 -4 5; 2 1 -3; 1 2 -6]
A = [2 -1 4; 3 4 -2; 1 4 2; -4 -1 3]
#A = [1 3; 1 2]
A = float(A)
A0 = copy(A)
B0 = copy(A)
C0 = copy(A)

4×3 Matrix{Float64}:
  2.0  -1.0   4.0
  3.0   4.0  -2.0
  1.0   4.0   2.0
 -4.0  -1.0   3.0

In [3]:
# function geqrfCGS!(A)
    m = size(A,1)
    n = size(A,2)
    @assert m >= n
    R = zeros(Float64, n,n)
    for j=1:n
      display("j=")
      display(j)
        # Orthogonalize
        for i=1:j-1, k=1:m
            R[i,j] += A[k,i] * A[k,j]
        end
        for i=1:j-1, k=1:m
            A[k,j] -= A[k,i] * R[i,j]
        end
        R[j,j] = norm( A[:,j] )
        display("Orthogonal columns of A before Normalization")
        display(A)
        display("Matrix R")
        display(R)
        # Normalize column
        A[:,j] /= R[j,j]
    display("Orthogonal columns of A after Normalization")
    display(A)
    end
    display("Q")
    display(A)
    # A contains the Q factor at the end
    display("R")
    display(R)
#     return R
# end

"j="

1

"Orthogonal columns of A before Normalization"

4×3 Matrix{Float64}:
  2.0  -1.0   4.0
  3.0   4.0  -2.0
  1.0   4.0   2.0
 -4.0  -1.0   3.0

"Matrix R"

3×3 Matrix{Float64}:
 5.47723  0.0  0.0
 0.0      0.0  0.0
 0.0      0.0  0.0

"Orthogonal columns of A after Normalization"

4×3 Matrix{Float64}:
  0.365148  -1.0   4.0
  0.547723   4.0  -2.0
  0.182574   4.0   2.0
 -0.730297  -1.0   3.0

"j="

2

"Orthogonal columns of A before Normalization"

4×3 Matrix{Float64}:
  0.365148  -2.2   4.0
  0.547723   2.2  -2.0
  0.182574   3.4   2.0
 -0.730297   1.4   3.0

"Matrix R"

3×3 Matrix{Float64}:
 5.47723  3.28634  0.0
 0.0      4.81664  0.0
 0.0      0.0      0.0

"Orthogonal columns of A after Normalization"

4×3 Matrix{Float64}:
  0.365148  -0.45675    4.0
  0.547723   0.45675   -2.0
  0.182574   0.705887   2.0
 -0.730297   0.290659   3.0

"j="

3

"Orthogonal columns of A before Normalization"

4×3 Matrix{Float64}:
  0.365148  -0.45675    4.32471
  0.547723   0.45675   -0.991379
  0.182574   0.705887   2.58908
 -0.730297   0.290659   2.06609

"Matrix R"

3×3 Matrix{Float64}:
 5.47723  3.28634  -1.46059
 0.0      4.81664  -0.45675
 0.0      0.0       5.53697

"Orthogonal columns of A after Normalization"

4×3 Matrix{Float64}:
  0.365148  -0.45675    0.781061
  0.547723   0.45675   -0.179047
  0.182574   0.705887   0.467599
 -0.730297   0.290659   0.373145

"Q"

4×3 Matrix{Float64}:
  0.365148  -0.45675    0.781061
  0.547723   0.45675   -0.179047
  0.182574   0.705887   0.467599
 -0.730297   0.290659   0.373145

"R"

3×3 Matrix{Float64}:
 5.47723  3.28634  -1.46059
 0.0      4.81664  -0.45675
 0.0      0.0       5.53697

In [11]:
A*R # Q*R

4×3 Matrix{Float64}:
  2.0  -1.0   4.0
  3.0   4.0  -2.0
  1.0   4.0   2.0
 -4.0  -1.0   3.0

In [5]:
A0  # matrix A

4×3 Matrix{Float64}:
  2.0  -1.0   4.0
  3.0   4.0  -2.0
  1.0   4.0   2.0
 -4.0  -1.0   3.0

In [6]:
function geqrfMGS!(A)
    m = size(A,1)
    n = size(A,2)
    @assert m >= n
    R = zeros(Float64, n,n)
    for j=1:n
        # Orthogonalize
        for i=1:j-1
            for k=1:m
                R[i,j] += A[k,i] * A[k,j]
            end
            for k=1:m
                A[k,j] -= A[k,i] * R[i,j]
            end
        end
        display("Orthogonal columns of A before Normalization")
        display(A)
        # Normalize column
        R[j,j] = norm( A[:,j] )
        A[:,j] /= R[j,j]
        display("matrix R")
        display(R)
        display("Orthogonal columns of A after Normalization")
        display(A)
    end
    display("Q")
    display(A)
    # A contains the Q factor at the end
    display("R")
    display(R)
    return R
end

geqrfMGS! (generic function with 1 method)

In [7]:
geqrfMGS!(B0)

"Orthogonal columns of A before Normalization"

4×3 Matrix{Float64}:
  2.0  -1.0   4.0
  3.0   4.0  -2.0
  1.0   4.0   2.0
 -4.0  -1.0   3.0

"matrix R"

3×3 Matrix{Float64}:
 5.47723  0.0  0.0
 0.0      0.0  0.0
 0.0      0.0  0.0

"Orthogonal columns of A after Normalization"

4×3 Matrix{Float64}:
  0.365148  -1.0   4.0
  0.547723   4.0  -2.0
  0.182574   4.0   2.0
 -0.730297  -1.0   3.0

"Orthogonal columns of A before Normalization"

4×3 Matrix{Float64}:
  0.365148  -2.2   4.0
  0.547723   2.2  -2.0
  0.182574   3.4   2.0
 -0.730297   1.4   3.0

"matrix R"

3×3 Matrix{Float64}:
 5.47723  3.28634  0.0
 0.0      4.81664  0.0
 0.0      0.0      0.0

"Orthogonal columns of A after Normalization"

4×3 Matrix{Float64}:
  0.365148  -0.45675    4.0
  0.547723   0.45675   -2.0
  0.182574   0.705887   2.0
 -0.730297   0.290659   3.0

"Orthogonal columns of A before Normalization"

4×3 Matrix{Float64}:
  0.365148  -0.45675    4.32471
  0.547723   0.45675   -0.991379
  0.182574   0.705887   2.58908
 -0.730297   0.290659   2.06609

"matrix R"

3×3 Matrix{Float64}:
 5.47723  3.28634  -1.46059
 0.0      4.81664  -0.45675
 0.0      0.0       5.53697

"Orthogonal columns of A after Normalization"

4×3 Matrix{Float64}:
  0.365148  -0.45675    0.781061
  0.547723   0.45675   -0.179047
  0.182574   0.705887   0.467599
 -0.730297   0.290659   0.373145

"Q"

4×3 Matrix{Float64}:
  0.365148  -0.45675    0.781061
  0.547723   0.45675   -0.179047
  0.182574   0.705887   0.467599
 -0.730297   0.290659   0.373145

"R"

3×3 Matrix{Float64}:
 5.47723  3.28634  -1.46059
 0.0      4.81664  -0.45675
 0.0      0.0       5.53697

3×3 Matrix{Float64}:
 5.47723  3.28634  -1.46059
 0.0      4.81664  -0.45675
 0.0      0.0       5.53697

In [8]:
B0*R #Q*R

4×3 Matrix{Float64}:
  2.0  -1.0   4.0
  3.0   4.0  -2.0
  1.0   4.0   2.0
 -4.0  -1.0   3.0

In [9]:
C0 # matrix A 

4×3 Matrix{Float64}:
  2.0  -1.0   4.0
  3.0   4.0  -2.0
  1.0   4.0   2.0
 -4.0  -1.0   3.0