In [22]:
using Printf
using Random
using LinearAlgebra
rng = MersenneTwister(18);

In [23]:
A = [1 1 1;-1 9 2;0 -1 2]
A = float(A)
n = size(A,1)
display(A)

3×3 Matrix{Float64}:
  1.0   1.0  1.0
 -1.0   9.0  2.0
  0.0  -1.0  2.0

In [24]:
Id = Matrix{Float64}(I, n, n)
P = zeros(n,n)
function anti_diagonal(Id)
    c = size(Id, 2)
    for i = 1:c
        P[:,i] = Id[:,c+1-i]
    end
    return P
end
P = anti_diagonal(Id)

3×3 Matrix{Float64}:
 0.0  0.0  1.0
 0.0  1.0  0.0
 1.0  0.0  0.0

In [26]:
λ = P*eigvals(A)
display("Eigenvalues of A")
display(λ)
X = eigvecs(A)
display("Eigenvectors of A")
X = X*P

"Eigenvalues of A"

3-element Vector{Float64}:
 8.584428340330486
 2.1948819130472557
 1.2206897466222526

"Eigenvectors of A"

3×3 Matrix{Float64}:
  0.109887   0.551634  -0.987861
  0.982676  -0.159547  -0.0954854
 -0.149242   0.818685  -0.122525

In [27]:
Λ = inv(X)*A*X

3×3 Matrix{Float64}:
 8.58443      -1.77636e-15  6.10623e-16
 1.38778e-15   2.19488      3.33067e-16
 4.30211e-15  -6.66134e-16  1.22069

In [39]:
qk = [1;1;1]
qk /= norm(qk)

μ0 = Λ[1,1]
μ =  9
# Our initial approximation of an eigenvalue of interest

println("Exact answer: ", μ0)
println("Initial guess: ", μ)

for k=1:15
    zk = (A - μ * I) \ qk
    qk = zk/norm(zk)       # Normalize e-vector
    ev = dot(qk, A * qk)   # Eigen-value approximation
    s = μ - ev
    println("Iteration: ",k," | eig-value: ", ev, " | Shift:", s)
end
display("Eigen-vector")
display(qk)

Exact answer: 8.58442834033049
Initial guess: 9
Iteration: 1 | eig-value: 8.646502835538753 | Shift:0.35349716446124724
Iteration: 2 | eig-value: 8.590104539539519 | Shift:0.409895460460481
Iteration: 3 | eig-value: 8.584783244047472 | Shift:0.41521675595252816
Iteration: 4 | eig-value: 8.584450128022667 | Shift:0.4155498719773334
Iteration: 5 | eig-value: 8.58442967576567 | Shift:0.4155703242343307
Iteration: 6 | eig-value: 8.584428422140288 | Shift:0.415571577859712
Iteration: 7 | eig-value: 8.584428345340188 | Shift:0.4155716546598125
Iteration: 8 | eig-value: 8.584428340637155 | Shift:0.4155716593628451
Iteration: 9 | eig-value: 8.58442834034926 | Shift:0.4155716596507393
Iteration: 10 | eig-value: 8.584428340331641 | Shift:0.41557165966835896
Iteration: 11 | eig-value: 8.584428340330561 | Shift:0.415571659669439
Iteration: 12 | eig-value: 8.584428340330495 | Shift:0.4155716596695047
Iteration: 13 | eig-value: 8.584428340330492 | Shift:0.41557165966950826
Iteration: 14 | eig-value:

"Eigen-vector"

3-element Vector{Float64}:
 -0.10988742520774158
 -0.9826756686582475
  0.14924236666670504

In [40]:
X[:,1]

3-element Vector{Float64}:
  0.109887425207742
  0.9826756686582475
 -0.14924236666670512