In [1]:
using LinearAlgebra
using Random
rng = MersenneTwister();

In [2]:
Random.seed!(rng, 2018)

# Size of the matrix
n = 4;

# Initialization of matrix A
#@show n
L = zeros(Float64,n,n)
U = zeros(Float64,n,n)
for i=1:n
    
    U[i,i] = i
    U[i,i+1:n] = rand(rng, 0:9, n-i)
    L[i,1:i] = rand(rng, 0:9, i)
    L[i,i] = 1
end
#L[3, [1,3,4]] = [1,0,1]
#L[4,[3,4]] = [1,0]
display("L,U =")
display(L)
display(U)
A = L * U
display("A=")
display(A)
n = size(A,1)

for k=1:n
    display(k)
    @assert A[k,k] != 0
    for i=k+1:n
        A[i,k] /= A[k,k]
    end

    # Outer-product of column k and row k
    for i=k+1:n
        for j=k+1:n
            A[i,j] -= A[i,k] * A[k,j]
        end
    end
    display("Ak=")
    display(A)
    
        
end

"L,U ="

4×4 Matrix{Float64}:
 1.0  0.0  0.0  0.0
 9.0  1.0  0.0  0.0
 9.0  5.0  1.0  0.0
 0.0  7.0  2.0  1.0

4×4 Matrix{Float64}:
 1.0  0.0  2.0  7.0
 0.0  2.0  6.0  9.0
 0.0  0.0  3.0  8.0
 0.0  0.0  0.0  4.0

"A="

4×4 Matrix{Float64}:
 1.0   0.0   2.0    7.0
 9.0   2.0  24.0   72.0
 9.0  10.0  51.0  116.0
 0.0  14.0  48.0   83.0

1

"Ak="

4×4 Matrix{Float64}:
 1.0   0.0   2.0   7.0
 9.0   2.0   6.0   9.0
 9.0  10.0  33.0  53.0
 0.0  14.0  48.0  83.0

2

"Ak="

4×4 Matrix{Float64}:
 1.0  0.0  2.0   7.0
 9.0  2.0  6.0   9.0
 9.0  5.0  3.0   8.0
 0.0  7.0  6.0  20.0

3

"Ak="

4×4 Matrix{Float64}:
 1.0  0.0  2.0  7.0
 9.0  2.0  6.0  9.0
 9.0  5.0  3.0  8.0
 0.0  7.0  2.0  4.0

4

"Ak="

4×4 Matrix{Float64}:
 1.0  0.0  2.0  7.0
 9.0  2.0  6.0  9.0
 9.0  5.0  3.0  8.0
 0.0  7.0  2.0  4.0

In [3]:
Random.seed!(rng, 2018)

# Size of the matrix
n = 4;

# Initialization of matrix A
@show n
L = zeros(Float64,n,n)
U = zeros(Float64,n,n)
for i=1:n
    
    U[i,i] = i
    U[i,i+1:n] = rand(rng, 0:9, n-i)
    L[i,1:i] = rand(rng, 0:9, i)
    L[i,i] = 1
end
#L[3, [1,3,4]] = [1,0,1]
#L[4,[3,4]] = [1,0]
display("L,U =")
display(L)
display(U)
A = L * U
display("A=")
display(A)
n = size(A,1)
L_c = tril(ones(Float64,n,n))
U_c = copy(A)
for k=1:n-1
    display(k)
    @assert A[k,k] != 0
    for i=k+1:n
        L_c[i,k]=U_c[i,k]/U_c[k,k]
    end

    # Outer-product of column k and row k
    for i=k+1:n
        for j=k:n
            U_c[i,j]= U_c[i,j] - L_c[i,k]*U_c[k,j]
        end
    end
    display("L=")
    display(L_c)
    display("U=")
    display(U_c)
        
end

"L,U ="

4×4 Matrix{Float64}:
 1.0  0.0  0.0  0.0
 9.0  1.0  0.0  0.0
 9.0  5.0  1.0  0.0
 0.0  7.0  2.0  1.0

4×4 Matrix{Float64}:
 1.0  0.0  2.0  7.0
 0.0  2.0  6.0  9.0
 0.0  0.0  3.0  8.0
 0.0  0.0  0.0  4.0

"A="

4×4 Matrix{Float64}:
 1.0   0.0   2.0    7.0
 9.0   2.0  24.0   72.0
 9.0  10.0  51.0  116.0
 0.0  14.0  48.0   83.0

1

"L="

4×4 Matrix{Float64}:
 1.0  0.0  0.0  0.0
 9.0  1.0  0.0  0.0
 9.0  1.0  1.0  0.0
 0.0  1.0  1.0  1.0

"U="

4×4 Matrix{Float64}:
 1.0   0.0   2.0   7.0
 0.0   2.0   6.0   9.0
 0.0  10.0  33.0  53.0
 0.0  14.0  48.0  83.0

2

"L="

4×4 Matrix{Float64}:
 1.0  0.0  0.0  0.0
 9.0  1.0  0.0  0.0
 9.0  5.0  1.0  0.0
 0.0  7.0  1.0  1.0

"U="

4×4 Matrix{Float64}:
 1.0  0.0  2.0   7.0
 0.0  2.0  6.0   9.0
 0.0  0.0  3.0   8.0
 0.0  0.0  6.0  20.0

3

"L="

4×4 Matrix{Float64}:
 1.0  0.0  0.0  0.0
 9.0  1.0  0.0  0.0
 9.0  5.0  1.0  0.0
 0.0  7.0  2.0  1.0

"U="

4×4 Matrix{Float64}:
 1.0  0.0  2.0  7.0
 0.0  2.0  6.0  9.0
 0.0  0.0  3.0  8.0
 0.0  0.0  0.0  4.0

n = 4


In [6]:
include("getrf_dc.jl")
n = 2
#ϵ = 1e-14
# ϵ = 1e-17 # Type \epsilon [TAB]
# ϵ = 64.0 * eps(Float64) / π 
 ϵ = eps(Float64) / π 
# ϵ = 0.25 * eps(Float64) / π
A = [ϵ 1; 1 π] # Type \pi [TAB]
A0 = copy(A)
getrfOuter!(A)
L = tril(A,-1) + UniformScaling(1)
U = triu(A)
println("L:\n",L)
println("U:\n",U)
println("LU:\n",L*U)
println("A:\n",A0)

L:


[1.0 0.0; 1.414847550405688e16 1.0]
U:
[7.067899292141149e-17 1.0; 0.0 -1.4148475504056876e16]
LU:
[7.067899292141149e-17 1.0; 1.0 4.0]
A:
[7.067899292141149e-17 1.0; 1.0 3.141592653589793]
