In [1]:
using LinearAlgebra
using Random
rng = MersenneTwister()
Random.seed!(rng, 2018)
output = false

false

LU factorization with pivoting on a random 6 x 6 matrix:

In [2]:
# Size of the matrix
n = 6;

# Random initialization of matrix A
L = zeros(Float64,n,n)
U = zeros(Float64,n,n)
P = randperm(rng,n) # Randow row permutation
for i=1:n
    L[P[i],i] = 3 # Largest entry in the column
    L[P[i+1:n],i] = rand(rng, 2:5, n-i)
    U[i,i] = rand(rng, 1:2)
    U[i,i+1:n] = rand(rng, 3:6, n-i)
end
A = L * U
A0 = copy(A);
B0 = copy(A)
display(A)

6×6 Matrix{Float64}:
 4.0  20.0  38.0  70.0  89.0  82.0
 4.0  20.0  38.0  66.0  79.0  82.0
 4.0  19.0  35.0  56.0  57.0  46.0
 3.0  15.0  24.0  33.0  36.0  30.0
 3.0  12.0  15.0  15.0  18.0  12.0
 2.0  11.0  27.0  58.0  65.0  51.0

Program to perform LU factorization with Partial pivoting:-

In [3]:
function getrf!(A)
    # Uses pivoting
    n = size(A,1)
    P = collect(1:n)
    for k=1:n
        display(k)
        # Find pivot
        imx = k - 1 + argmax( abs.(A[k:end,k]) ) # row with largest entry
        # Swap rows
        for j=1:n
            A[k,j],A[imx,j] = A[imx,j],A[k,j]
        end
        P[[k,imx]] = P[[imx,k]]
        println("matrix A after row permutation=")
        display(A)
        # Proceed with factorization
        for i=k+1:n
            A[i,k] /= A[k,k]
        end

        for j=k+1:n, i=k+1:n
            A[i,j] -= A[i,k] * A[k,j]
        end
        println("matrix after L U factorization=")
        display(A)
    end
    return P
end

getrf! (generic function with 1 method)

In [4]:
getrf!(A)
A

1

matrix A after row permutation=


6×6 Matrix{Float64}:
 4.0  20.0  38.0  70.0  89.0  82.0
 4.0  20.0  38.0  66.0  79.0  82.0
 4.0  19.0  35.0  56.0  57.0  46.0
 3.0  15.0  24.0  33.0  36.0  30.0
 3.0  12.0  15.0  15.0  18.0  12.0
 2.0  11.0  27.0  58.0  65.0  51.0

matrix after L U factorization=


6×6 Matrix{Float64}:
 4.0   20.0   38.0   70.0   89.0    82.0
 1.0    0.0    0.0   -4.0  -10.0     0.0
 1.0   -1.0   -3.0  -14.0  -32.0   -36.0
 0.75   0.0   -4.5  -19.5  -30.75  -31.5
 0.75  -3.0  -13.5  -37.5  -48.75  -49.5
 0.5    1.0    8.0   23.0   20.5    10.0

2

matrix A after row permutation=


6×6 Matrix{Float64}:
 4.0   20.0   38.0   70.0   89.0    82.0
 0.75  -3.0  -13.5  -37.5  -48.75  -49.5
 1.0   -1.0   -3.0  -14.0  -32.0   -36.0
 0.75   0.0   -4.5  -19.5  -30.75  -31.5
 1.0    0.0    0.0   -4.0  -10.0     0.0
 0.5    1.0    8.0   23.0   20.5    10.0

matrix after L U factorization=


6×6 Matrix{Float64}:
 4.0   20.0        38.0   70.0   89.0    82.0
 0.75  -3.0       -13.5  -37.5  -48.75  -49.5
 1.0    0.333333    1.5   -1.5  -15.75  -19.5
 0.75  -0.0        -4.5  -19.5  -30.75  -31.5
 1.0   -0.0         0.0   -4.0  -10.0     0.0
 0.5   -0.333333    3.5   10.5    4.25   -6.5

3

matrix A after row permutation=


6×6 Matrix{Float64}:
 4.0   20.0        38.0   70.0   89.0    82.0
 0.75  -3.0       -13.5  -37.5  -48.75  -49.5
 0.75  -0.0        -4.5  -19.5  -30.75  -31.5
 1.0    0.333333    1.5   -1.5  -15.75  -19.5
 1.0   -0.0         0.0   -4.0  -10.0     0.0
 0.5   -0.333333    3.5   10.5    4.25   -6.5

matrix after L U factorization=


6×6 Matrix{Float64}:
 4.0   20.0        38.0        70.0       89.0      82.0
 0.75  -3.0       -13.5       -37.5      -48.75    -49.5
 0.75  -0.0        -4.5       -19.5      -30.75    -31.5
 1.0    0.333333   -0.333333   -8.0      -26.0     -30.0
 1.0   -0.0        -0.0        -4.0      -10.0       0.0
 0.5   -0.333333   -0.777778   -4.66667  -19.6667  -31.0

4

matrix A after row permutation=


6×6 Matrix{Float64}:
 4.0   20.0        38.0        70.0       89.0      82.0
 0.75  -3.0       -13.5       -37.5      -48.75    -49.5
 0.75  -0.0        -4.5       -19.5      -30.75    -31.5
 1.0    0.333333   -0.333333   -8.0      -26.0     -30.0
 1.0   -0.0        -0.0        -4.0      -10.0       0.0
 0.5   -0.333333   -0.777778   -4.66667  -19.6667  -31.0

matrix after L U factorization=


6×6 Matrix{Float64}:
 4.0   20.0        38.0        70.0        89.0    82.0
 0.75  -3.0       -13.5       -37.5       -48.75  -49.5
 0.75  -0.0        -4.5       -19.5       -30.75  -31.5
 1.0    0.333333   -0.333333   -8.0       -26.0   -30.0
 1.0   -0.0        -0.0         0.5         3.0    15.0
 0.5   -0.333333   -0.777778    0.583333   -4.5   -13.5

5

matrix A after row permutation=


6×6 Matrix{Float64}:
 4.0   20.0        38.0        70.0        89.0    82.0
 0.75  -3.0       -13.5       -37.5       -48.75  -49.5
 0.75  -0.0        -4.5       -19.5       -30.75  -31.5
 1.0    0.333333   -0.333333   -8.0       -26.0   -30.0
 0.5   -0.333333   -0.777778    0.583333   -4.5   -13.5
 1.0   -0.0        -0.0         0.5         3.0    15.0

matrix after L U factorization=


6×6 Matrix{Float64}:
 4.0   20.0        38.0        70.0        89.0        82.0
 0.75  -3.0       -13.5       -37.5       -48.75      -49.5
 0.75  -0.0        -4.5       -19.5       -30.75      -31.5
 1.0    0.333333   -0.333333   -8.0       -26.0       -30.0
 0.5   -0.333333   -0.777778    0.583333   -4.5       -13.5
 1.0   -0.0        -0.0         0.5        -0.666667    6.0

6

matrix A after row permutation=


6×6 Matrix{Float64}:
 4.0   20.0        38.0        70.0        89.0        82.0
 0.75  -3.0       -13.5       -37.5       -48.75      -49.5
 0.75  -0.0        -4.5       -19.5       -30.75      -31.5
 1.0    0.333333   -0.333333   -8.0       -26.0       -30.0
 0.5   -0.333333   -0.777778    0.583333   -4.5       -13.5
 1.0   -0.0        -0.0         0.5        -0.666667    6.0

matrix after L U factorization=


6×6 Matrix{Float64}:
 4.0   20.0        38.0        70.0        89.0        82.0
 0.75  -3.0       -13.5       -37.5       -48.75      -49.5
 0.75  -0.0        -4.5       -19.5       -30.75      -31.5
 1.0    0.333333   -0.333333   -8.0       -26.0       -30.0
 0.5   -0.333333   -0.777778    0.583333   -4.5       -13.5
 1.0   -0.0        -0.0         0.5        -0.666667    6.0

6×6 Matrix{Float64}:
 4.0   20.0        38.0        70.0        89.0        82.0
 0.75  -3.0       -13.5       -37.5       -48.75      -49.5
 0.75  -0.0        -4.5       -19.5       -30.75      -31.5
 1.0    0.333333   -0.333333   -8.0       -26.0       -30.0
 0.5   -0.333333   -0.777778    0.583333   -4.5       -13.5
 1.0   -0.0        -0.0         0.5        -0.666667    6.0

In [5]:
L = tril(A,-1) + UniformScaling(1)
U = triu(A)
println("L:\n")
display(L)
println("U:\n")
display(U)
println("LU:\n")
display(L*U)

L:



6×6 Matrix{Float64}:
 1.0    0.0        0.0       0.0        0.0       0.0
 0.75   1.0        0.0       0.0        0.0       0.0
 0.75  -0.0        1.0       0.0        0.0       0.0
 1.0    0.333333  -0.333333  1.0        0.0       0.0
 0.5   -0.333333  -0.777778  0.583333   1.0       0.0
 1.0   -0.0       -0.0       0.5       -0.666667  1.0

U:



6×6 Matrix{Float64}:
 4.0  20.0   38.0   70.0   89.0    82.0
 0.0  -3.0  -13.5  -37.5  -48.75  -49.5
 0.0   0.0   -4.5  -19.5  -30.75  -31.5
 0.0   0.0    0.0   -8.0  -26.0   -30.0
 0.0   0.0    0.0    0.0   -4.5   -13.5
 0.0   0.0    0.0    0.0    0.0     6.0

LU:



6×6 Matrix{Float64}:
 4.0  20.0  38.0  70.0  89.0  82.0
 3.0  12.0  15.0  15.0  18.0  12.0
 3.0  15.0  24.0  33.0  36.0  30.0
 4.0  19.0  35.0  56.0  57.0  46.0
 2.0  11.0  27.0  58.0  65.0  51.0
 4.0  20.0  38.0  66.0  79.0  82.0

Program to perform LU factorization with Full pivoting:-

In [6]:
println("matrix A=")
display(A0)

matrix A=


6×6 Matrix{Float64}:
 4.0  20.0  38.0  70.0  89.0  82.0
 4.0  20.0  38.0  66.0  79.0  82.0
 4.0  19.0  35.0  56.0  57.0  46.0
 3.0  15.0  24.0  33.0  36.0  30.0
 3.0  12.0  15.0  15.0  18.0  12.0
 2.0  11.0  27.0  58.0  65.0  51.0

In [7]:
function getrfFull!(A)
    # Full pivoting 
    n = size(A,1)
    P_row = collect(1:n); P_col = collect(1:n);
    for k=1:n-1
        display(k)
        # Full pivoting
        index = findmax(abs.(A[k:end, k:end]))[2]
        row = index[1]
        col = index[2]
        # If we reach this line, this means that the pivot is the largest
        # in its row and column.
        row += k-1; col += k-1
        # Swap rows and columns
        P_row[k], P_row[row] = P_row[row], P_row[k]
        P_col[k], P_col[col] = P_col[col], P_col[k]
        for j=1:n
            A[k,j],A[row,j] = A[row,j],A[k,j]
        end
        for i=1:n
            A[i,k],A[i,col] = A[i,col],A[i,k]
        end
        println("After swaping rows and columns")
        display(A)
        # Perform usual LU step
        if A[k,k] != 0
            for i=k+1:n
                A[i,k] /= A[k,k]
            end
            for j=k+1:n, i=k+1:n
                A[i,j] -= A[i,k] * A[k,j]
            end
        end
        println("matrix after L U factorization=")
        display(A)
    end
    return P_row, P_col
end

getrfFull! (generic function with 1 method)

In [8]:
getrfFull!(A)
A

1

After swaping rows and columns


6×6 Matrix{Float64}:
  89.0       20.0        38.0        70.0       4.0    82.0
 -48.75      -3.0       -13.5       -37.5       0.75  -49.5
 -30.75      -0.0        -4.5       -19.5       0.75  -31.5
 -26.0        0.333333   -0.333333   -8.0       1.0   -30.0
  -4.5       -0.333333   -0.777778    0.583333  0.5   -13.5
  -0.666667  -0.0        -0.0         0.5       1.0     6.0

matrix after L U factorization=


6×6 Matrix{Float64}:
 89.0         20.0       38.0       70.0       4.0       82.0
 -0.547753     7.95506    7.31461    0.842697  2.94101   -4.58427
 -0.345506     6.91011    8.62921    4.68539   2.13202   -3.16854
 -0.292135     6.17603   10.7678    12.4494    2.16854   -6.04494
 -0.0505618    0.677903   1.14357    4.12266   0.702247  -9.35393
 -0.00749064   0.149813   0.284644   1.02434   1.02996    6.61423

2

After swaping rows and columns


6×6 Matrix{Float64}:
 89.0         70.0       38.0       20.0       4.0       82.0
 -0.292135    12.4494    10.7678     6.17603   2.16854   -6.04494
 -0.345506     4.68539    8.62921    6.91011   2.13202   -3.16854
 -0.547753     0.842697   7.31461    7.95506   2.94101   -4.58427
 -0.0505618    4.12266    1.14357    0.677903  0.702247  -9.35393
 -0.00749064   1.02434    0.284644   0.149813  1.02996    6.61423

matrix after L U factorization=


6×6 Matrix{Float64}:
 89.0         70.0        38.0       20.0        4.0        82.0
 -0.292135    12.4494     10.7678     6.17603    2.16854    -6.04494
 -0.345506     0.376354    4.57671    4.58574    1.31588    -0.893502
 -0.547753     0.0676895   6.58574    7.537      2.79422    -4.17509
 -0.0505618    0.331152   -2.42221   -1.3673    -0.0158694  -7.35214
 -0.00749064   0.0822804  -0.601334  -0.358353   0.851534    7.11161

3

After swaping rows and columns


6×6 Matrix{Float64}:
 89.0         70.0        20.0       38.0        4.0        82.0
 -0.292135    12.4494      6.17603   10.7678     2.16854    -6.04494
 -0.547753     0.0676895   7.537      6.58574    2.79422    -4.17509
 -0.345506     0.376354    4.58574    4.57671    1.31588    -0.893502
 -0.0505618    0.331152   -1.3673    -2.42221   -0.0158694  -7.35214
 -0.00749064   0.0822804  -0.358353  -0.601334   0.851534    7.11161

matrix after L U factorization=


6×6 Matrix{Float64}:
 89.0         70.0        20.0        38.0        4.0       82.0
 -0.292135    12.4494      6.17603    10.7678     2.16854   -6.04494
 -0.547753     0.0676895   7.537       6.58574    2.79422   -4.17509
 -0.345506     0.376354    0.60843     0.569752  -0.384205   1.64675
 -0.0505618    0.331152   -0.181412   -1.22747    0.491037  -8.10955
 -0.00749064   0.0822804  -0.0475459  -0.288209   0.984388   6.9131

4

After swaping rows and columns


6×6 Matrix{Float64}:
 89.0         70.0        20.0        82.0       4.0       38.0
 -0.292135    12.4494      6.17603    -6.04494   2.16854   10.7678
 -0.547753     0.0676895   7.537      -4.17509   2.79422    6.58574
 -0.0505618    0.331152   -0.181412   -8.10955   0.491037  -1.22747
 -0.345506     0.376354    0.60843     1.64675  -0.384205   0.569752
 -0.00749064   0.0822804  -0.0475459   6.9131    0.984388  -0.288209

matrix after L U factorization=


6×6 Matrix{Float64}:
 89.0         70.0        20.0        82.0        4.0       38.0
 -0.292135    12.4494      6.17603    -6.04494    2.16854   10.7678
 -0.547753     0.0676895   7.537      -4.17509    2.79422    6.58574
 -0.0505618    0.331152   -0.181412   -8.10955    0.491037  -1.22747
 -0.345506     0.376354    0.60843    -0.203063  -0.284494   0.320498
 -0.00749064   0.0822804  -0.0475459  -0.852465   1.40298   -1.33459

5

After swaping rows and columns


6×6 Matrix{Float64}:
 89.0         70.0        20.0        82.0        4.0       38.0
 -0.292135    12.4494      6.17603    -6.04494    2.16854   10.7678
 -0.547753     0.0676895   7.537      -4.17509    2.79422    6.58574
 -0.0505618    0.331152   -0.181412   -8.10955    0.491037  -1.22747
 -0.00749064   0.0822804  -0.0475459  -0.852465   1.40298   -1.33459
 -0.345506     0.376354    0.60843    -0.203063  -0.284494   0.320498

matrix after L U factorization=


6×6 Matrix{Float64}:
 89.0         70.0        20.0        82.0        4.0       38.0
 -0.292135    12.4494      6.17603    -6.04494    2.16854   10.7678
 -0.547753     0.0676895   7.537      -4.17509    2.79422    6.58574
 -0.0505618    0.331152   -0.181412   -8.10955    0.491037  -1.22747
 -0.00749064   0.0822804  -0.0475459  -0.852465   1.40298   -1.33459
 -0.345506     0.376354    0.60843    -0.203063  -0.202779   0.0498717

6×6 Matrix{Float64}:
 89.0         70.0        20.0        82.0        4.0       38.0
 -0.292135    12.4494      6.17603    -6.04494    2.16854   10.7678
 -0.547753     0.0676895   7.537      -4.17509    2.79422    6.58574
 -0.0505618    0.331152   -0.181412   -8.10955    0.491037  -1.22747
 -0.00749064   0.0822804  -0.0475459  -0.852465   1.40298   -1.33459
 -0.345506     0.376354    0.60843    -0.203063  -0.202779   0.0498717

In [9]:
L = tril(A,-1) + UniformScaling(1)
U = triu(A)
println("L:\n")
display(L)
println("U:\n")
display(U)
println("LU:\n")
display(L*U)

L:



6×6 Matrix{Float64}:
  1.0         0.0         0.0         0.0        0.0       0.0
 -0.292135    1.0         0.0         0.0        0.0       0.0
 -0.547753    0.0676895   1.0         0.0        0.0       0.0
 -0.0505618   0.331152   -0.181412    1.0        0.0       0.0
 -0.00749064  0.0822804  -0.0475459  -0.852465   1.0       0.0
 -0.345506    0.376354    0.60843    -0.203063  -0.202779  1.0

U:



6×6 Matrix{Float64}:
 89.0  70.0     20.0      82.0      4.0       38.0
  0.0  12.4494   6.17603  -6.04494  2.16854   10.7678
  0.0   0.0      7.537    -4.17509  2.79422    6.58574
  0.0   0.0      0.0      -8.10955  0.491037  -1.22747
  0.0   0.0      0.0       0.0      1.40298   -1.33459
  0.0   0.0      0.0       0.0      0.0        0.0498717

LU:



6×6 Matrix{Float64}:
  89.0        70.0       20.0           82.0  4.0    38.0
 -26.0        -8.0        0.333333     -30.0  1.0    -0.333333
 -48.75      -37.5       -3.0          -49.5  0.75  -13.5
  -4.5         0.583333  -0.333333     -13.5  0.5    -0.777778
  -0.666667    0.5        4.63755e-18    6.0  1.0     0.0
 -30.75      -19.5        3.60939e-16  -31.5  0.75   -4.5

Program to perform LU factorization with Rook pivoting:-

In [10]:
println("matrix A=")
display(B0)

matrix A=


6×6 Matrix{Float64}:
 4.0  20.0  38.0  70.0  89.0  82.0
 4.0  20.0  38.0  66.0  79.0  82.0
 4.0  19.0  35.0  56.0  57.0  46.0
 3.0  15.0  24.0  33.0  36.0  30.0
 3.0  12.0  15.0  15.0  18.0  12.0
 2.0  11.0  27.0  58.0  65.0  51.0

In [11]:
function getrfRook!(A)
    # Rook pivoting for rank-revealing LU
    n = size(A,1)
    P_row = collect(1:n); P_col = collect(1:n);
    for k=1:n
        display(k)
        # Rook pivoting
        row = 1; row0 = 0; col = 1; col0 = 0
        while row != row0 || col != col0
            row0, col0 = row, col # Save old values
            row_A = abs.(A[row+k-1, k:end]) # Search in pivots' row
            col = argmax(row_A)
            col_A = abs.(A[k:end, col+k-1]) # Search in pivot's column
            row = argmax(col_A)
        end
        # If we reach this line, this means that the pivot is the largest
        # in its row and column.
        row += k-1; col += k-1
        # Swap rows and columns
        P_row[k], P_row[row] = P_row[row], P_row[k]
        P_col[k], P_col[col] = P_col[col], P_col[k]
        for j=1:n
            A[k,j],A[row,j] = A[row,j],A[k,j]
        end
        for i=1:n
            A[i,k],A[i,col] = A[i,col],A[i,k]
        end
        println("After swaping rows and columns")
        display(A)
        # Perform usual LU step
        if A[k,k] != 0
            for i=k+1:n
                A[i,k] /= A[k,k]
            end
            for j=k+1:n, i=k+1:n
                A[i,j] -= A[i,k] * A[k,j]
            end
        end
        println("matrix after L U factorization=")
        display(A)
    end
    return P_row, P_col
end

getrfRook! (generic function with 1 method)

In [12]:
getrfRook!(A)
A

1

After swaping rows and columns


6×6 Matrix{Float64}:
 89.0         70.0        20.0        82.0        4.0       38.0
 -0.292135    12.4494      6.17603    -6.04494    2.16854   10.7678
 -0.547753     0.0676895   7.537      -4.17509    2.79422    6.58574
 -0.0505618    0.331152   -0.181412   -8.10955    0.491037  -1.22747
 -0.00749064   0.0822804  -0.0475459  -0.852465   1.40298   -1.33459
 -0.345506     0.376354    0.60843    -0.203063  -0.202779   0.0498717

matrix after L U factorization=


6×6 Matrix{Float64}:
 89.0         70.0        20.0        82.0        4.0       38.0
 -0.00328241  12.6792      6.24168    -5.77579    2.18167   10.8925
 -0.00615453   0.498506    7.66009    -3.67042    2.81884    6.81961
 -0.00056811   0.37092    -0.17005    -8.06296    0.493309  -1.20589
 -8.41645e-5   0.0881719  -0.0458626  -0.845563   1.40332   -1.33139
 -0.00388209   0.6481      0.686072    0.115268  -0.18725    0.197391

2

After swaping rows and columns


6×6 Matrix{Float64}:
 89.0         70.0        20.0        82.0        4.0       38.0
 -0.00328241  12.6792      6.24168    -5.77579    2.18167   10.8925
 -0.00615453   0.498506    7.66009    -3.67042    2.81884    6.81961
 -0.00056811   0.37092    -0.17005    -8.06296    0.493309  -1.20589
 -8.41645e-5   0.0881719  -0.0458626  -0.845563   1.40332   -1.33139
 -0.00388209   0.6481      0.686072    0.115268  -0.18725    0.197391

matrix after L U factorization=


6×6 Matrix{Float64}:
 89.0         70.0         20.0        82.0        4.0       38.0
 -0.00328241  12.6792       6.24168    -5.77579    2.18167   10.8925
 -0.00615453   0.0393168    7.41469    -3.44333    2.73307    6.39135
 -0.00056811   0.0292542   -0.352645   -7.894      0.429486  -1.52454
 -8.41645e-5   0.00695405  -0.0892676  -0.805398   1.38814   -1.40714
 -0.00388209   0.0511152    0.367027    0.410498  -0.298767  -0.359382

3

After swaping rows and columns


6×6 Matrix{Float64}:
 89.0         70.0         20.0        82.0        4.0       38.0
 -0.00328241  12.6792       6.24168    -5.77579    2.18167   10.8925
 -0.00615453   0.0393168    7.41469    -3.44333    2.73307    6.39135
 -0.00056811   0.0292542   -0.352645   -7.894      0.429486  -1.52454
 -8.41645e-5   0.00695405  -0.0892676  -0.805398   1.38814   -1.40714
 -0.00388209   0.0511152    0.367027    0.410498  -0.298767  -0.359382

matrix after L U factorization=


6×6 Matrix{Float64}:
 89.0         70.0         20.0        82.0        4.0       38.0
 -0.00328241  12.6792       6.24168    -5.77579    2.18167   10.8925
 -0.00615453   0.0393168    7.41469    -3.44333    2.73307    6.39135
 -0.00056811   0.0292542   -0.0475603  -8.05776    0.559471  -1.22056
 -8.41645e-5   0.00695405  -0.0120393  -0.846853   1.42105   -1.33019
 -0.00388209   0.0511152    0.0495      0.580943  -0.434053  -0.675754

4

After swaping rows and columns


6×6 Matrix{Float64}:
 89.0         70.0         20.0        82.0        4.0       38.0
 -0.00328241  12.6792       6.24168    -5.77579    2.18167   10.8925
 -0.00615453   0.0393168    7.41469    -3.44333    2.73307    6.39135
 -0.00056811   0.0292542   -0.0475603  -8.05776    0.559471  -1.22056
 -8.41645e-5   0.00695405  -0.0120393  -0.846853   1.42105   -1.33019
 -0.00388209   0.0511152    0.0495      0.580943  -0.434053  -0.675754

matrix after L U factorization=


6×6 Matrix{Float64}:
 89.0         70.0         20.0        82.0         4.0       38.0
 -0.00328241  12.6792       6.24168    -5.77579     2.18167   10.8925
 -0.00615453   0.0393168    7.41469    -3.44333     2.73307    6.39135
 -0.00056811   0.0292542   -0.0475603  -8.05776     0.559471  -1.22056
 -8.41645e-5   0.00695405  -0.0120393   0.105098    1.36225   -1.20191
 -0.00388209   0.0511152    0.0495     -0.0720974  -0.393717  -0.763754

5

After swaping rows and columns


6×6 Matrix{Float64}:
 89.0         70.0         20.0        82.0         4.0       38.0
 -0.00328241  12.6792       6.24168    -5.77579     2.18167   10.8925
 -0.00615453   0.0393168    7.41469    -3.44333     2.73307    6.39135
 -0.00056811   0.0292542   -0.0475603  -8.05776     0.559471  -1.22056
 -8.41645e-5   0.00695405  -0.0120393   0.105098    1.36225   -1.20191
 -0.00388209   0.0511152    0.0495     -0.0720974  -0.393717  -0.763754

matrix after L U factorization=


6×6 Matrix{Float64}:
 89.0         70.0         20.0        82.0         4.0       38.0
 -0.00328241  12.6792       6.24168    -5.77579     2.18167   10.8925
 -0.00615453   0.0393168    7.41469    -3.44333     2.73307    6.39135
 -0.00056811   0.0292542   -0.0475603  -8.05776     0.559471  -1.22056
 -8.41645e-5   0.00695405  -0.0120393   0.105098    1.36225   -1.20191
 -0.00388209   0.0511152    0.0495     -0.0720974  -0.28902   -1.11113

6

After swaping rows and columns


6×6 Matrix{Float64}:
 89.0         70.0         20.0        82.0         4.0       38.0
 -0.00328241  12.6792       6.24168    -5.77579     2.18167   10.8925
 -0.00615453   0.0393168    7.41469    -3.44333     2.73307    6.39135
 -0.00056811   0.0292542   -0.0475603  -8.05776     0.559471  -1.22056
 -8.41645e-5   0.00695405  -0.0120393   0.105098    1.36225   -1.20191
 -0.00388209   0.0511152    0.0495     -0.0720974  -0.28902   -1.11113

matrix after L U factorization=


6×6 Matrix{Float64}:
 89.0         70.0         20.0        82.0         4.0       38.0
 -0.00328241  12.6792       6.24168    -5.77579     2.18167   10.8925
 -0.00615453   0.0393168    7.41469    -3.44333     2.73307    6.39135
 -0.00056811   0.0292542   -0.0475603  -8.05776     0.559471  -1.22056
 -8.41645e-5   0.00695405  -0.0120393   0.105098    1.36225   -1.20191
 -0.00388209   0.0511152    0.0495     -0.0720974  -0.28902   -1.11113

6×6 Matrix{Float64}:
 89.0         70.0         20.0        82.0         4.0       38.0
 -0.00328241  12.6792       6.24168    -5.77579     2.18167   10.8925
 -0.00615453   0.0393168    7.41469    -3.44333     2.73307    6.39135
 -0.00056811   0.0292542   -0.0475603  -8.05776     0.559471  -1.22056
 -8.41645e-5   0.00695405  -0.0120393   0.105098    1.36225   -1.20191
 -0.00388209   0.0511152    0.0495     -0.0720974  -0.28902   -1.11113

In [13]:
L = tril(A,-1) + UniformScaling(1)
U = triu(A)
println("L:\n")
display(L)
println("U:\n")
display(U)
println("LU:\n")
display(L*U)

L:



6×6 Matrix{Float64}:
  1.0         0.0          0.0         0.0         0.0      0.0
 -0.00328241  1.0          0.0         0.0         0.0      0.0
 -0.00615453  0.0393168    1.0         0.0         0.0      0.0
 -0.00056811  0.0292542   -0.0475603   1.0         0.0      0.0
 -8.41645e-5  0.00695405  -0.0120393   0.105098    1.0      0.0
 -0.00388209  0.0511152    0.0495     -0.0720974  -0.28902  1.0

U:



6×6 Matrix{Float64}:
 89.0  70.0     20.0      82.0      4.0       38.0
  0.0  12.6792   6.24168  -5.77579  2.18167   10.8925
  0.0   0.0      7.41469  -3.44333  2.73307    6.39135
  0.0   0.0      0.0      -8.05776  0.559471  -1.22056
  0.0   0.0      0.0       0.0      1.36225   -1.20191
  0.0   0.0      0.0       0.0      0.0       -1.11113

LU:



6×6 Matrix{Float64}:
 89.0         70.0        20.0        82.0        4.0       38.0
 -0.292135    12.4494      6.17603    -6.04494    2.16854   10.7678
 -0.547753     0.0676895   7.537      -4.17509    2.79422    6.58574
 -0.0505618    0.331152   -0.181412   -8.10955    0.491037  -1.22747
 -0.00749064   0.0822804  -0.0475459  -0.852465   1.40298   -1.33459
 -0.345506     0.376354    0.60843    -0.203063  -0.202779   0.0498717