In [1]:
using Printf
using Random
using LinearAlgebra
rng = MersenneTwister(18);

In [2]:
A = [1 1 1;-1 9 2;0 -1 2]
A = float(A)
n = size(A,1)
display(A)

3×3 Matrix{Float64}:
  1.0   1.0  1.0
 -1.0   9.0  2.0
  0.0  -1.0  2.0

In [3]:
Id = Matrix{Float64}(I, n, n)
P = zeros(n,n)
function anti_diagonal(Id)
    c = size(Id, 2)
    for i = 1:c
        P[:,i] = Id[:,c+1-i]
    end
    return P
end
P = anti_diagonal(Id)

3×3 Matrix{Float64}:
 0.0  0.0  1.0
 0.0  1.0  0.0
 1.0  0.0  0.0

In [4]:
λ = P*eigvals(A)
display("Eigenvalues of A")
display(λ)
X = eigvecs(A)
display("Eigenvectors of A")
X = X*P

"Eigenvalues of A"

3-element Vector{Float64}:
 8.584428340330486
 2.1948819130472557
 1.2206897466222526

"Eigenvectors of A"

3×3 Matrix{Float64}:
  0.109887   0.551634  -0.987861
  0.982676  -0.159547  -0.0954854
 -0.149242   0.818685  -0.122525

In [5]:
Λ = inv(X)*A*X

3×3 Matrix{Float64}:
 8.58443      -1.77636e-15  6.10623e-16
 1.38778e-15   2.19488      3.33067e-16
 4.30211e-15  -6.66134e-16  1.22069

In [8]:
x1 = X[:,1]
x1 /= norm(x1)

qk  = [1;1;1] #starting vector
qk /= norm(qk)

niter = 10
err = zeros(niter)

for k=1:niter
    display(k)
    zk = A * qk          # Power iteration: multiply by A
    eval = dot(zk,qk)    # E-value approximation
    qk = zk/norm(zk)     # Normalize e-vector
    if (qk[1]*x1[1] < 0)
        qk = -qk
    end
#     λ1= qk*zk
#     display(λ1)
    display("qk")
    display(qk)
    err = abs(Λ[1,1] - eval)
end
display("x1")
display(x1)
print("error=", err)

1

"qk"

3-element Vector{Float64}:
 0.2860387767736777
 0.9534625892455922
 0.09534625892455922

2

"qk"

3-element Vector{Float64}:
  0.1547835629215539
  0.9839812214298782
 -0.08844775024088793

3

"qk"

3-element Vector{Float64}:
  0.12118973673787305
  0.9835503897357908
 -0.13394655113133336

4

"qk"

3-element Vector{Float64}:
  0.11275442924786909
  0.9829341440609244
 -0.14535097909613612

5

"qk"

3-element Vector{Float64}:
  0.11061756667035008
  0.9827441224784158
 -0.14824892471130796

6

"qk"

3-element Vector{Float64}:
  0.11007372205695083
  0.9826933423270501
 -0.1489884916985881

7

"qk"

3-element Vector{Float64}:
  0.10993500458080924
  0.9826802011409213
 -0.1491774683169551

8

"qk"

3-element Vector{Float64}:
  0.10989958291373603
  0.9826768287747922
 -0.1492257747994783

9

"qk"

3-element Vector{Float64}:
  0.10989053265633637
  0.9826759654102002
 -0.149238124611769

10

"qk"

3-element Vector{Float64}:
  0.10988821957614278
  0.982675744548012
 -0.1492412820750211

"x1"

3-element Vector{Float64}:
  0.109887425207742
  0.9826756686582475
 -0.14924236666670512

error=7.526281001091206e-6