In [1]:
using Printf
using Random
using LinearAlgebra
rng = MersenneTwister(18);

In [2]:
include("gees_dc.jl")

gees_testsuite (generic function with 1 method)

In [3]:
n = 10
Λ = diagm(0 => Float32[2.0^(-i) for i=0:n-3])
A = zeros(n,n)
A[1:n-2,1:n-2] = Λ
A[n-1:n,n-1:n] = [0 1; -1 0]
display(A)
X = rand(rng, n, n)
#display(Λ)
# Λ = diagm(Float32[2.0^(-i) for i=0:n-1])
# A = Λ
# X, = qr(rand(rng, n, n))

A = X * A / X

println("Matrix A")
pretty_print(A)
Λ = eigenvalue_sorted(A)

10×10 Matrix{Float64}:
 1.0  0.0  0.0   0.0    0.0     0.0      0.0       0.0         0.0  0.0
 0.0  0.5  0.0   0.0    0.0     0.0      0.0       0.0         0.0  0.0
 0.0  0.0  0.25  0.0    0.0     0.0      0.0       0.0         0.0  0.0
 0.0  0.0  0.0   0.125  0.0     0.0      0.0       0.0         0.0  0.0
 0.0  0.0  0.0   0.0    0.0625  0.0      0.0       0.0         0.0  0.0
 0.0  0.0  0.0   0.0    0.0     0.03125  0.0       0.0         0.0  0.0
 0.0  0.0  0.0   0.0    0.0     0.0      0.015625  0.0         0.0  0.0
 0.0  0.0  0.0   0.0    0.0     0.0      0.0       0.0078125   0.0  0.0
 0.0  0.0  0.0   0.0    0.0     0.0      0.0       0.0         0.0  1.0
 0.0  0.0  0.0   0.0    0.0     0.0      0.0       0.0        -1.0  0.0

Matrix A
  6.4e-01  1.8e+00  7.8e-01 -4.6e+00  8.2e-01  1.7e+00 -1.0e+00  2.0e+00 -9.2e-01 -2.5e-01
  5.0e-01  2.0e+00 -6.8e-01 -1.5e+00 -1.3e-01  1.4e+00 -1.8e+00  1.8e+00 -9.6e-01  8.0e-01
  3.7e-01  1.5e+00 -7.1e-03 -2.6e+00  3.1e-01  1.4e+00 -1.1e+00  1.6e+00 -7.7e-01  2.9e-01
  4.5e-01  1.3e+00 -3.5e-01 -2.1e+00  3.9e-01  1.3e+00 -1.2e+00  1.4e+00 -6.8e-01  3.8e-01
  3.1e-01  2.6e+00 -1.9e-01 -3.9e+00  4.5e-01  2.4e+00 -1.8e+00  2.7e+00 -1.4e+00  5.5e-01
  1.1e-01  1.2e+00 -5.2e-01 -1.6e+00  1.6e-01  1.4e+00 -1.0e+00  1.4e+00 -6.8e-01  5.0e-01
  7.5e-02  1.3e+00 -5.4e-01 -8.9e-01 -2.3e-01  1.1e+00 -1.0e+00  1.2e+00 -6.4e-01  7.3e-01
  1.2e-01  6.1e-01 -3.4e-01 -5.7e-01  1.0e-02  6.0e-01 -6.1e-01  6.9e-01 -3.1e-01  3.8e-01
  4.1e-01  1.8e-03  1.3e-01 -2.1e+00  8.9e-01  6.7e-01 -7.7e-02  5.0e-01  7.1e-04 -2.6e-01
  9.3e-02  7.7e-01  4.9e-01 -2.8e+00  5.7e-01  1.1e+00 -2.3e-01  1.1e+00 -4.4e-01 -1.0e-01


10-element Vector{ComplexF64}:
   0.007812499999999143 + 0.0im
   0.015625000000000513 + 0.0im
    0.03124999999999937 + 0.0im
    0.06250000000000006 + 0.0im
    0.12499999999999928 + 0.0im
    0.24999999999999986 + 0.0im
     0.5000000000000008 + 0.0im
 -7.389922007661198e-16 - 1.0im
 -7.389922007661198e-16 + 1.0im
     1.0000000000000007 + 0.0im

In [4]:
# Applying Householder reflections to make matrix A upper Hessenberg
gehrd!(A)
A0 = copy(A)
#A[10,9]=0
pretty_print(A)
D0=eigenvalue_sorted(A0)

  6.4e-01  7.0e-01  2.1e-01  2.0e+00  9.3e-01 -2.0e+00 -1.0e+00 -1.0e+00 -3.8e+00  2.9e+00
 -9.5e-01 -8.0e-01 -1.6e-01 -2.7e+00 -7.3e-01  3.0e+00  1.0e+00 -1.5e+00  5.8e+00 -5.3e+00
 -5.6e-17 -6.5e-01  3.5e-01 -1.4e+00 -2.8e-01  1.4e+00  6.4e-01  1.4e+00  2.3e+00 -1.3e+00
 -1.1e-16  0.0e+00  7.0e-01  1.0e+00  3.6e-01 -1.2e+00 -8.5e-01  1.8e+00 -2.3e+00  2.9e+00
 -5.6e-17  0.0e+00  5.6e-17 -1.8e-01  1.4e-01  3.6e-01  1.2e-01 -1.1e+00  7.0e-01 -9.7e-01
 -2.8e-17  0.0e+00  6.9e-18  0.0e+00  2.1e-01  2.4e-01 -6.5e-02 -8.9e-01  3.1e-01 -5.5e-01
 -1.4e-17  0.0e+00  2.8e-17  0.0e+00  3.5e-18  1.2e-01  2.8e-01 -3.2e-01  2.7e-01 -3.6e-01
 -2.8e-17  0.0e+00 -1.4e-17  0.0e+00 -1.7e-18  0.0e+00  1.1e-02  2.1e-02  2.2e-02 -4.1e-02
 -1.1e-16  0.0e+00 -1.1e-16  0.0e+00  6.9e-18  0.0e+00 -8.7e-19  7.0e-03  1.2e-02  1.7e-02
 -1.4e-17  0.0e+00  1.7e-18  0.0e+00 -1.4e-17  0.0e+00  1.7e-18  0.0e+00 -1.7e-02  6.6e-02


10-element Vector{ComplexF64}:
  0.007812499999998361 + 0.0im
   0.01562500000000069 + 0.0im
  0.031249999999997176 + 0.0im
   0.06250000000000008 + 0.0im
   0.12500000000000078 + 0.0im
   0.24999999999999964 + 0.0im
     0.500000000000001 + 0.0im
 6.938893903907228e-16 - 1.0000000000000002im
 6.938893903907228e-16 + 1.0000000000000002im
     1.000000000000003 + 0.0im

In [5]:
# Checking that A is upper Hessenberg now
println("Norm for lower part of matrix = ",norm(tril(A,-2)))

Norm for lower part of matrix = 2.2231041417055534e-16


In [6]:
n = size(A,1)
    if n==1
        return fill(A[1,1],1)
    end
    D = zeros(Complex{Float64},n)

    # Tolerance for deflation
    tol = eps(Float64)

    q = n # Size of the matrix we are currently working with
    iter = 1 # Counter to detect convergence failure
    iter_per_evalue = 0 # Used to trigger an exceptional shift

    # Zero out small entries
    reduce_eps!(A, tol)

    while q > 0
        println("q=",q)
        pretty_print(A)
        if iter > 10*n
            println("Failure to converge")
            println("Size of matrix = ",n)
            println("Eigenvalues found:")
            println(D)
            D1 = eigenvalue_sorted(A)
            println("Remaining eigenvalues at point of failure:")
            println(D1)
            return D # The eigenvalues we were able to calculate up to the failure
        end

        deflation = true # Were we able to deflate the matrix?

        while deflation
            deflation = false
            # Test for convergence
            # Test deflation for the last 2x2 block
            if q <= 2 || A[q-1,q-2] == 0
                if q >= 2
                    # The last 2x2 block has converged
                    deflation = true # Deflating now
                    println("2x2 deflation")
                    # Compute the eigenvalues
                    a = A[q-1,q-1]; b = A[q-1,q]; c = A[q,q-1]; d = A[q,q]
                    # Last 2x2 block
                    htr = (a+d)/2         # Half-trace
                    dis = (a-d)^2/4 + b*c # Discriminant
                    if dis > 0 # Pair of real eigenvalues
                        D[q-1] = htr - sqrt(dis)
                        D[q]   = htr + sqrt(dis)
                    else # Complex conjugate eigenvalues
                        D[q-1] = htr - sqrt(-dis)*im
                        D[q]   = htr + sqrt(-dis)*im
                    end
                    # Reduce the size of the matrix
                    q -= 2
                    if q>=1
                        A = A[1:q,1:q]
                    end
                end
            end

            if q==0
                return D
            end

            # Testing deflation for the last 1x1 block
            if q <= 1 || A[q,q-1] == 0
                deflation = true
                println("1x1 deflation")
                D[q] = A[q,q]
                q -= 1
                if q>=1
                    A = A[1:q,1:q]
                end
            end

            if q==0
                return D
            end

            if deflation
                iter_per_evalue = 0 # Reset the counter
            end
        end

        # If q <= 2 we will compute the eigenvalues at the next iteration
        if q >= 3
            # Searching for the smallest unreduced sub-block
            p = q
            while p > 1 && A[p,p-1] != 0
                p -= 1
            end

            # If the unreduced sub-block has size 2 or less, we move on
            # to the next iteration.
            if q-p+1 >= 3
                B = A[p:q,p:q] # Extract sub-block
                exceptional_shift = ((iter_per_evalue%5) == 0 &&
                                      iter_per_evalue>0)
                # Francis QR step
                gees_single_step!(B, exceptional_shift)
                # Reduce matrix
                reduce_eps!(B, tol)
                A[p:q,p:q] = B # Copy the resulting matrix back
                iter += 1 # Increment iteration counter
                iter_per_evalue += 1
                # Increment counter for exceptional_shift
            end
        end
    end

q=10
  6.4e-01  7.0e-01  2.1e-01  2.0e+00  9.3e-01 -2.0e+00 -1.0e+00 -1.0e+00 -3.8e+00  2.9e+00
 -9.5e-01 -8.0e-01 -1.6e-01 -2.7e+00 -7.3e-01  3.0e+00  1.0e+00 -1.5e+00  5.8e+00 -5.3e+00
 -5.6e-17 -6.5e-01  3.5e-01 -1.4e+00 -2.8e-01  1.4e+00  6.4e-01  1.4e+00  2.3e+00 -1.3e+00
 -1.1e-16  0.0e+00  7.0e-01  1.0e+00  3.6e-01 -1.2e+00 -8.5e-01  1.8e+00 -2.3e+00  2.9e+00
 -5.6e-17  0.0e+00  5.6e-17 -1.8e-01  1.4e-01  3.6e-01  1.2e-01 -1.1e+00  7.0e-01 -9.7e-01
 -2.8e-17  0.0e+00  6.9e-18  0.0e+00  2.1e-01  2.4e-01 -6.5e-02 -8.9e-01  3.1e-01 -5.5e-01
 -1.4e-17  0.0e+00  2.8e-17  0.0e+00  3.5e-18  1.2e-01  2.8e-01 -3.2e-01  2.7e-01 -3.6e-01
 -2.8e-17  0.0e+00 -1.4e-17  0.0e+00 -1.7e-18  0.0e+00  1.1e-02  2.1e-02  2.2e-02 -4.1e-02
 -1.1e-16  0.0e+00 -1.1e-16  0.0e+00  6.9e-18  0.0e+00 -8.7e-19  7.0e-03  1.2e-02  1.7e-02
 -1.4e-17  0.0e+00  1.7e-18  0.0e+00 -1.4e-17  0.0e+00  1.7e-18  0.0e+00 -1.7e-02  6.6e-02
q=10
  3.7e-02  2.9e+00 -1.3e+00  5.3e-01 -2.1e+00 -2.3e+00 -9.7e-01 -2.2e+00 -4.2e+0

10-element Vector{ComplexF64}:
 8.881784197001252e-16 - 1.0000000000000007im
 8.881784197001252e-16 + 1.0000000000000007im
    1.0000000000000024 + 0.0im
    0.5000000000000016 + 0.0im
     0.125000000000001 + 0.0im
   0.24999999999999978 + 0.0im
  0.007812499999997892 + 0.0im
  0.031249999999996794 + 0.0im
   0.01562500000000125 + 0.0im
   0.06250000000000004 + 0.0im

In [7]:
D2 = gees!(A0)
D2 = eigenvalue_sorted(diagm(0 => D2)) 
#we use the previous line to just sort the eigenvalues, dont really use the inbuilt eigen
display(D2)

D1 = eigenvalue_sorted(A0)
#pretty_print(A)
@show norm(D0 - D2)
@show norm(D1 - D2)

#@assert norm(D0 - D2) < 1e-7
#@assert norm(D1 - D2) < 1e-7


10-element Vector{ComplexF64}:
  0.007812499999997892 + 0.0im
   0.01562500000000125 + 0.0im
  0.031249999999996794 + 0.0im
   0.06250000000000004 + 0.0im
     0.125000000000001 + 0.0im
   0.24999999999999978 + 0.0im
    0.5000000000000016 + 0.0im
 8.881784197001252e-16 - 1.0000000000000007im
 8.881784197001252e-16 + 1.0000000000000007im
    1.0000000000000024 + 0.0im

norm(D0 - D2) = 1.4032615570571384e-15
norm(D1 - D2) = 1.7646435657016817e-15


1.7646435657016817e-15