In [1]:
using Random
using LinearAlgebra
rng = MersenneTwister(2018)
import LinearAlgebra.dot
import LinearAlgebra.norm
import LinearAlgebra.cond
import LinearAlgebra.triu
import LinearAlgebra.qr
import LinearAlgebra.UniformScaling;
# A = [2 -2 18; 2 1 0; 1 2 0]
A = [1 -1 4; 1 4 -2; 1 4 2; 1 -1 0]
A = float(A)
A0 = copy(A)
#n = 4
#x = rand(rng, n)

4×3 Matrix{Float64}:
 1.0  -1.0   4.0
 1.0   4.0  -2.0
 1.0   4.0   2.0
 1.0  -1.0   0.0

In [2]:
function house(x)
    """Computes the Householder transformation for input vector x"""
    sigma = dot(x[2:end],x[2:end])
    v = copy(x)

    if sigma == 0
        beta = 0
        return beta, v
    end

    sq = sqrt(x[1]^2 + sigma)
    if x[1] > 0
        v[1] += sq
    else
        v[1] -= sq
    end

    beta = 2.0 / (v[1]^2 + sigma)

    return beta, v
end


house (generic function with 1 method)

In [3]:
#function geqrf!(A)
    m = size(A,1)
    n = size(A,2)
    vA = zeros(n)
    E = Matrix{Float64}(I, m, m)
    kend = (m > n ? n : m-1)
    #display(kend)
   Q = copy(E)
display("A_initial")
display(A)
    for k=1:kend
        beta, v = house(A[k:end,k])
     display("k")
    display(k)
   # new_row = zeros(k-1)
    #v = vcat(new_row, v)
    display("beta")
    display(beta)
    display("v")
    display(v)
    #v = v/v[1,1]
    #display("modified v")
    #display(v)
    G = Matrix{Float64}(I, m-k+1, m-k+1) - beta*v*v'

    P = copy(E)
    P = float(P)
    P[k:end, k:end] = G
    display("P")
    display(P)
    
    Q = Q*P
    
    #v = v/v(1)
        for j=k:n
            # vA = beta * v^T * A
            vA[j] = 0.0
            for i=k:m
                vA[j] += v[i-k+1] * A[i,j]
            end
            vA[j] *= beta
        end
        # A - beta v (v^T A)
        for j=k:n, i=k:m
            A[i,j] -= v[i-k+1] * vA[j]
        end
    display("A")
    display(A)
    
       display("normalized v")
    v = v/v[1]
    display(v)
        A[k+1:end,k] = v[2:end]
    display("modified A")
    display(A)
        # Saving v in the lower triangular part of A.
        # This was not done here but one can always
        # divide v by v[1] such that v[1] = 1 is always true.
        # In that case, v[1] does not need to be stored.
    end
    display("Q")
    display(Q)
    # Lower triangular part of A: sequence of v vectors
    # Upper triangular part: factor R
#end

"A_initial"

4×3 Matrix{Float64}:
 1.0  -1.0   4.0
 1.0   4.0  -2.0
 1.0   4.0   2.0
 1.0  -1.0   0.0

"k"

1

"beta"

0.16666666666666666

"v"

4-element Vector{Float64}:
 3.0
 1.0
 1.0
 1.0

"P"

4×4 Matrix{Float64}:
 -0.5  -0.5       -0.5       -0.5
 -0.5   0.833333  -0.166667  -0.166667
 -0.5  -0.166667   0.833333  -0.166667
 -0.5  -0.166667  -0.166667   0.833333

"A"

4×3 Matrix{Float64}:
 -2.0  -3.0      -2.0
  0.0   3.33333  -4.0
  0.0   3.33333   0.0
  0.0  -1.66667  -2.0

"normalized v"

4-element Vector{Float64}:
 1.0
 0.3333333333333333
 0.3333333333333333
 0.3333333333333333

"modified A"

4×3 Matrix{Float64}:
 -2.0       -3.0      -2.0
  0.333333   3.33333  -4.0
  0.333333   3.33333   0.0
  0.333333  -1.66667  -2.0

"k"

2

"beta"

0.023999999999999997

"v"

3-element Vector{Float64}:
  8.333333333333334
  3.3333333333333335
 -1.6666666666666665

"P"

4×4 Matrix{Float64}:
 1.0   0.0        0.0       0.0
 0.0  -0.666667  -0.666667  0.333333
 0.0  -0.666667   0.733333  0.133333
 0.0   0.333333   0.133333  0.933333

"A"

4×3 Matrix{Float64}:
 -2.0       -3.0  -2.0
  0.333333  -5.0   2.0
  0.333333   0.0   2.4
  0.333333   0.0  -3.2

"normalized v"

3-element Vector{Float64}:
  1.0
  0.39999999999999997
 -0.19999999999999996

"modified A"

4×3 Matrix{Float64}:
 -2.0       -3.0  -2.0
  0.333333  -5.0   2.0
  0.333333   0.4   2.4
  0.333333  -0.2  -3.2

"k"

3

"beta"

0.03906249999999999

"v"

2-element Vector{Float64}:
  6.4
 -3.2

"P"

4×4 Matrix{Float64}:
 1.0  0.0   0.0  0.0
 0.0  1.0   0.0  0.0
 0.0  0.0  -0.6  0.8
 0.0  0.0   0.8  0.6

"A"

4×3 Matrix{Float64}:
 -2.0       -3.0  -2.0
  0.333333  -5.0   2.0
  0.333333   0.4  -4.0
  0.333333  -0.2  -4.44089e-16

"normalized v"

2-element Vector{Float64}:
  1.0
 -0.5

"modified A"

4×3 Matrix{Float64}:
 -2.0       -3.0  -2.0
  0.333333  -5.0   2.0
  0.333333   0.4  -4.0
  0.333333  -0.2  -0.5

"Q"

4×4 Matrix{Float64}:
 -0.5   0.5  -0.5  -0.5
 -0.5  -0.5   0.5  -0.5
 -0.5  -0.5  -0.5   0.5
 -0.5   0.5   0.5   0.5

In [5]:
R = triu(A)

4×3 Matrix{Float64}:
 -2.0  -3.0  -2.0
  0.0  -5.0   2.0
  0.0   0.0  -4.0
  0.0   0.0   0.0

In [6]:
Q*R

4×3 Matrix{Float64}:
 1.0  -1.0   4.0
 1.0   4.0  -2.0
 1.0   4.0   2.0
 1.0  -1.0   2.22045e-16

In [7]:
A0

4×3 Matrix{Float64}:
 1.0  -1.0   4.0
 1.0   4.0  -2.0
 1.0   4.0   2.0
 1.0  -1.0   0.0