In [1]:
using Printf
using Random
using LinearAlgebra
rng = MersenneTwister(18);

In [2]:
function pretty_print(v)
    @printf "["
    for i=1:length(v)
        @printf "%8.5f" v[i]
        if i < length(v)
            @printf "  "
        end
    end
    @printf "]\n"
end    

pretty_print (generic function with 1 method)

In [3]:
# Size of matrix
n = 4
X = rand(rng, n, n)    
X = qr(X)                     #QR factorization
X = X.Q                       #extract Q matrix
Λ = diagm(0 => Float32[3.0^(-i) for i=0:n-1])          #diagonal matrix
display("diagonal matrix")
display(Λ)
A = X * Λ / X

"diagonal matrix"

4×4 Matrix{Float32}:
 1.0  0.0       0.0       0.0
 0.0  0.333333  0.0       0.0
 0.0  0.0       0.111111  0.0
 0.0  0.0       0.0       0.037037

4×4 Matrix{Float64}:
 0.541977  0.203832  0.197409  0.154696
 0.203832  0.428252  0.225456  0.288801
 0.197409  0.225456  0.250478  0.14067
 0.154696  0.288801  0.14067   0.260774

In [4]:
r = 2
Qk = rand(rng, n, r)
for k=1:10
    Qk = A * Qk
    F = qr(Qk); 
    Qk = F.Q
    
     # This step is optional; it makes the solution unique
    for j=1:2
        if Qk[1,j] * X[1,j] < 0
            Qk[:,j] = -Qk[:,j]
            # This avoids sign differences
        end
    end
    println("\nIteration ",k)
    upper_triangular_check =  Qk'*A*Qk
    display("Upper traingular check")
    display(upper_triangular_check)
    
    
    #pretty_print(Qk[:,1])
    #pretty_print(X[:,1])
    ##pretty_print(Qk[:,2])
    #pretty_print(X[:,2])
end

 orthogonality_check = dot(Qk[:,1],Qk[:,2])
display("orthogonality_check")
display(orthogonality_check)
final_upper_triangular =  Qk'*A*Qk
display("final_upper_triangular")
display(final_upper_triangular)


Iteration 1


"Upper traingular check"

4×4 Matrix{Float64}:
 0.999723     0.00639907   0.0128109   0.00640794
 0.00639907   0.325716    -0.0332042   0.0239915
 0.0128109   -0.0332042    0.1088     -0.0262128
 0.00640794   0.0239915   -0.0262128   0.0472428


Iteration 2


"Upper traingular check"

4×4 Matrix{Float64}:
  0.999994     0.00170326  -0.00116266  0.000249934
  0.00170326   0.332507     0.0132728   0.00284413
 -0.00116266   0.0132728    0.110994    0.00835025
  0.000249934  0.00284413   0.00835025  0.0379862

"Upper traingular check"


Iteration 3


4×4 Matrix{Float64}:
  1.0          0.000547036  -0.000125928  9.30847e-6
  0.000547036  0.333242      0.00450939   0.000318241
 -0.000125928  0.00450939    0.1111       0.0027589
  9.30847e-6   0.000318241   0.0027589    0.0371399

"Upper traingular check"


Iteration 4


4×4 Matrix{Float64}:
  1.0          0.000181558  -1.39518e-5   3.44971e-7
  0.000181558  0.333323      0.0015063    3.53877e-5
 -1.39518e-5   0.0015063     0.11111      0.000918681
  3.44971e-7   3.53877e-5    0.000918681  0.0370484

"Upper traingular check"


Iteration 5


4×4 Matrix{Float64}:
  1.0         6.04901e-5   -1.5497e-6    1.27776e-8
  6.04901e-5  0.333332      0.000502216  3.9323e-6
 -1.5497e-6   0.000502216   0.111111     0.000306192
  1.27776e-8  3.9323e-6     0.000306192  0.0370383

"Upper traingular check"


Iteration 6


4×4 Matrix{Float64}:
  1.0          2.01623e-5  -1.72183e-7   4.73247e-10
  2.01623e-5   0.333333     0.00016741   4.36927e-7
 -1.72183e-7   0.00016741   0.111111     0.000102063
  4.73247e-10  4.36927e-7   0.000102063  0.0370372


Iteration 7


"Upper traingular check"

4×4 Matrix{Float64}:
  1.0          6.72072e-6  -1.91314e-8  1.75275e-11
  6.72072e-6   0.333333     5.58034e-5  4.85474e-8
 -1.91314e-8   5.58034e-5   0.111111    3.40208e-5
  1.75276e-11  4.85474e-8   3.40208e-5  0.0370371


Iteration 8


"Upper traingular check"

4×4 Matrix{Float64}:
  1.0          2.24024e-6  -2.12571e-9  6.49147e-13
  2.24024e-6   0.333333     1.86011e-5  5.39416e-9
 -2.12571e-9   1.86011e-5   0.111111    1.13403e-5
  6.49214e-13  5.39416e-9   1.13403e-5  0.037037

"Upper traingular check"


Iteration 9


4×4 Matrix{Float64}:
  1.0          7.46746e-7   -2.3619e-10  2.39808e-14
  7.46746e-7   0.333333      6.20038e-6  5.99351e-10
 -2.3619e-10   6.20038e-6    0.111111    3.78009e-6
  2.40966e-14  5.99351e-10   3.78009e-6  0.037037


Iteration 10


"Upper traingular check"

4×4 Matrix{Float64}:
  1.0          2.48915e-7   -2.62433e-11  1.11022e-15
  2.48915e-7   0.333333      2.06679e-6   6.65946e-11
 -2.62433e-11  2.06679e-6    0.111111     1.26003e-6
  9.74047e-16  6.65946e-11   1.26003e-6   0.037037

"orthogonality_check"

2.7755575615628914e-16

"final_upper_triangular"

4×4 Matrix{Float64}:
  1.0          2.48915e-7   -2.62433e-11  1.11022e-15
  2.48915e-7   0.333333      2.06679e-6   6.65946e-11
 -2.62433e-11  2.06679e-6    0.111111     1.26003e-6
  9.74047e-16  6.65946e-11   1.26003e-6   0.037037

In [5]:
Qk = rand(rng, n, r)
niter = 30
err = zeros(niter,2)

for k=1:niter
    Qk = A * Qk
    F = qr(Qk)
    Qk = Matrix(F.Q); Rk = F.R
    for j=1:2
        if Qk[1,j] * X[1,j] < 0
            Qk[:,j] = -Qk[:,j]
        end
        err[k,j] = norm(Qk[:,j] - X[:,j])
    end
end
err

30×2 Matrix{Float64}:
 0.0993932    1.50369
 0.0263208    1.12647
 0.00849237   0.687808
 0.00282022   0.273876
 0.000939682  0.0936421
 0.000313213  0.0313054
 0.000104404  0.0104386
 3.48012e-5   0.00347964
 1.16004e-5   0.00115989
 3.8668e-6    0.000386629
 1.28893e-6   0.000128876
 4.29645e-7   4.29587e-5
 1.43215e-7   1.43196e-5
 ⋮            
 1.96454e-10  1.96428e-8
 6.54846e-11  6.54759e-9
 2.18282e-11  2.18253e-9
 7.27607e-12  7.2751e-10
 2.42535e-12  2.42503e-10
 8.08357e-13  8.08343e-11
 2.69437e-13  2.69446e-11
 8.97403e-14  8.98139e-12
 2.99351e-14  2.99373e-12
 9.89345e-15  9.97854e-13
 3.20285e-15  3.32524e-13
 1.10047e-15  1.10897e-13