In [4]:
using LinearAlgebra
using Random
rng = MersenneTwister();

In [14]:
Random.seed!(rng, 2018)

# Size of the matrix
n = 4;

# Initialization of matrix A
@show n
L = zeros(Float64,n,n)
x_true=rand(rng,1:9,n)
for i=1:n
    L[i,1:i] = rand(rng, 1:9, i)
    
end
#L[3, [1,3,4]] = [1,0,1]
#L[4,[3,4]] = [1,0]
display("L,x_true =")
display(L)
display(x)
b = L * x_true
display("b=")
display(b)


"L,x_true ="

4×4 Matrix{Float64}:
 6.0  0.0  0.0  0.0
 9.0  9.0  0.0  0.0
 3.0  8.0  9.0  0.0
 6.0  4.0  1.0  7.0

4-element Vector{Int64}:
 1
 2
 7
 6

"b="

4-element Vector{Float64}:
  6.0
 27.0
 82.0
 63.0

n = 4


In [16]:
n = length(b)
x = Vector{Float64}(undef,n)
for i=1:n
    z = 0.0
    for j = 1:i-1
        z += L[i,j] * x[j]
    end
    x[i] = (b[i] - z) / L[i,i]
    display([i x[i]])
end
display(x)

1×2 Matrix{Float64}:
 1.0  1.0

1×2 Matrix{Float64}:
 2.0  2.0

1×2 Matrix{Float64}:
 3.0  7.0

1×2 Matrix{Float64}:
 4.0  6.0

4-element Vector{Float64}:
 1.0
 2.0
 7.0
 6.0

In [17]:
n = length(b)
    x = copy(b)
    for j = 1:n
        x[j] = x[j] / L[j,j]
        for i = j+1:n
            x[i] -= L[i,j] * x[j]
            # This is fast because the row index is the inner loop
        end
        display(x')
    end
    

1×4 adjoint(::Vector{Float64}) with eltype Float64:
 1.0  18.0  79.0  57.0

1×4 adjoint(::Vector{Float64}) with eltype Float64:
 1.0  2.0  63.0  49.0

1×4 adjoint(::Vector{Float64}) with eltype Float64:
 1.0  2.0  7.0  42.0

1×4 adjoint(::Vector{Float64}) with eltype Float64:
 1.0  2.0  7.0  6.0